name: virica
description: "A new Flutter project for XYZ purpose."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  firebase_core_web: ^2.10.0 
  flutter_native_contact_picker: ^0.0.6
  email_validator: ^2.1.17
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  local_auth: ^2.1.7
  firebase_messaging: ^14.7.6
  contacts_service: ^0.6.3
  js: ^0.6.7
  js_promise: ^0.1.0
  # image_picker: ^1.0.7
  flutter_html: ^3.0.0-beta.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^3.0.1

flutter_icons: 
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/virica_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Samarkan
      fonts:
        - asset: assets/fonts/samarkan.ttf
